-- =====================================================
-- Giving Without Limit (GWL) — Production MySQL Schema
-- cPanel / phpMyAdmin friendly
--
-- Notes:
-- - Create DB + user in cPanel first, then select the DB in phpMyAdmin.
-- - This script does NOT run CREATE DATABASE.
-- - Uses VARCHAR(32) hex ids (generated by PHP: bin2hex(random_bytes(16))).
-- =====================================================

-- PROFILES (auth)
CREATE TABLE IF NOT EXISTS profiles (
  id VARCHAR(32) PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  role ENUM('admin','staff','volunteer','user') NOT NULL DEFAULT 'user',
  location TEXT,
  phone VARCHAR(50),
  department VARCHAR(100),
  position VARCHAR(100),
  bio TEXT,
  avatar_url TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_profiles_email ON profiles(email);
CREATE INDEX idx_profiles_role ON profiles(role);

-- EVENTS
CREATE TABLE IF NOT EXISTS events (
  id VARCHAR(32) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  date DATETIME NOT NULL,
  location TEXT,
  status VARCHAR(20) DEFAULT 'upcoming',
  image_url TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_events_date ON events(date);

-- EVENT MEDIA
CREATE TABLE IF NOT EXISTS event_media (
  id VARCHAR(32) PRIMARY KEY,
  event_id VARCHAR(32) NOT NULL,
  media_url TEXT NOT NULL,
  media_type VARCHAR(20) NOT NULL,
  title VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_event_media_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_event_media_event_id ON event_media(event_id);

-- HELP ME CAMPAIGNS
CREATE TABLE IF NOT EXISTS help_me_campaigns (
  id VARCHAR(32) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  target_amount DECIMAL(12,2) NOT NULL,
  current_amount DECIMAL(12,2) DEFAULT 0,
  closing_date DATETIME,
  status VARCHAR(20) DEFAULT 'active',
  beneficiary_name VARCHAR(255),
  image_url TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_campaigns_status ON help_me_campaigns(status);

-- VOLUNTEER APPLICATIONS
CREATE TABLE IF NOT EXISTS volunteer_applications (
  id VARCHAR(32) PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(50),
  interest_area VARCHAR(255),
  bio TEXT,
  status VARCHAR(20) DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_volunteers_status ON volunteer_applications(status);

-- IMPACT RECORDS
CREATE TABLE IF NOT EXISTS impact_records (
  id VARCHAR(32) PRIMARY KEY,
  type VARCHAR(20) NOT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT,
  media_url TEXT,
  thumbnail_url TEXT,
  category VARCHAR(50),
  is_featured TINYINT(1) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_impact_category ON impact_records(category);

-- FIELD REPORTS
CREATE TABLE IF NOT EXISTS field_reports (
  id VARCHAR(32) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  summary TEXT,
  full_report LONGTEXT,
  beneficiaries INT DEFAULT 0,
  location VARCHAR(255),
  category VARCHAR(255),
  status VARCHAR(20) DEFAULT 'draft',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_field_reports_status ON field_reports(status);

-- AI LEADS (public lead capture)
CREATE TABLE IF NOT EXISTS ai_leads (
  id VARCHAR(32) PRIMARY KEY,
  type VARCHAR(50) NOT NULL,
  full_name VARCHAR(255),
  email VARCHAR(255),
  amount VARCHAR(50),
  program_info TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_ai_leads_type ON ai_leads(type);

-- PASSWORD RESETS
CREATE TABLE IF NOT EXISTS password_resets (
  email VARCHAR(255) PRIMARY KEY,
  token VARCHAR(255) NOT NULL,
  expires_at DATETIME NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_password_resets_token ON password_resets(token);

-- DONATIONS (Paystack)
CREATE TABLE IF NOT EXISTS donations (
  id VARCHAR(32) PRIMARY KEY,
  donor_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  frequency VARCHAR(30) DEFAULT 'one-time',
  program VARCHAR(255) DEFAULT 'General Fund',
  status VARCHAR(20) DEFAULT 'pending',
  payment_id VARCHAR(255),
  message TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_donations_status ON donations(status);
CREATE INDEX idx_donations_created_at ON donations(created_at);

-- Optional: first admin user (replace email)
-- UPDATE profiles SET role='admin' WHERE email='you@example.com';
